config/routes.rb
Rails.application.routes.draw do
	root "pages#home"
	scope "(:locale)", locale: /en|zh-TW/ do
		root "pages#home"
		controller :pages do
			get 'home', to: "pages#home"
			get 'about', to: "pages#about"
		  get 'products', to: "pages#products"
		  get 'contact', to: "pages#contact_us"
		  get 'download', to: "pages#download"
		end
    resources :products
    resources :stories
    resources :catalogues
  	resources :categories do
      member do
        get "children", to: "categories#children"
        get "products", to: "categories#products"
      end
    end
    post 'contact_us', to: "contacts#create"
	end

  namespace :admin do
    root to: "pages#home"
    get "pages/home"
    resources :users, only: [:edit, :update]
    resources :stories
    resources :products do
      collection do
        post "reorder"
      end
    end
    resources :varieties, except: [:show]
  	resources :catalogues
  	resources :categories
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/pages/home.html.erb
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-3 col-md-6 col-sm-6">
				<%= link_to admin_catalogues_path do %>
					<div class="card card-stats">
						<div class="card-header card-header-warning card-header-icon">
							<div class="card-icon">
								<i class="material-icons">library_books</i>
							</div>
							<p class="card-category">目錄總計</p>
							<h3 class="card-title"> <%= Catalogue.all.size %>
								<small>冊</small>
							</h3>
						</div>
						<div class="card-footer">
							<div class="stats">
								<i class="material-icons">update</i>
								<% if Catalogue.all.size > 0 %>
									<%= Catalogue.order(updated_at: :desc).first.updated_at.strftime("%F") %>
								<% else %>
									<%= Time.zone.today %>
								<% end %>
							</div>
						</div>
					</div>
				<% end %>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<%= link_to admin_products_path do %>
					<div class="card card-stats">
						<div class="card-header card-header-danger card-header-icon">
							<div class="card-icon">
								<i class="material-icons">store</i>
							</div>
							<p class="card-category">產品數量</p>
							<h3 class="card-title"> <%= Product.all.size %>
								<small>個</small>
							</h3>
						</div>
						<div class="card-footer">
							<div class="stats">
								<i class="material-icons">update</i>
								<% if Product.all.size > 0 %>
									<%= Product.order(updated_at: :desc).first.updated_at.strftime("%F") %>
								<% else %>
									<%= Time.zone.today %>
								<% end %>
							</div>
						</div>
					</div>
				<% end %>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<%= link_to admin_stories_path do %>
					<div class="card card-stats">
						<div class="card-header card-header-info card-header-icon">
							<div class="card-icon">
								<i class="material-icons">info_outline</i>
							</div>
							<p class="card-category">消息總計</p>
							<h3 class="card-title"><%= Story.all.size %>
								<small>則</small>
							</h3>
						</div>
						<div class="card-footer">
							<div class="stats">
								<i class="material-icons">update</i>
								<% if Story.all.size > 0 %>
									<%= Story.order(updated_at: :desc).first.updated_at.strftime("%F") %>
								<% else %>
									<%= Time.zone.today %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="card card-stats">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">cloud</i>
						</div>
						<p class="card-category">網站運行</p>
						<h3 class="card-title"><%= (Time.zone.today - Date.new(2018,6,1)).to_i %>
							<small>天</small>
						</h3>
					</div>
					<div class="card-footer">
						<div class="stats">
							<i class="material-icons">update</i> <%= Time.zone.today %>
						</div>
					</div>
				</div>
			</div>
		</div>
<!-- 		<div class="row">
			<div class="col-md-4">
				<div class="card card-chart">
					<div class="card-header card-header-success">
						<div class="ct-chart" id="dailySalesChart"></div>
					</div>
					<div class="card-body">
						<h4 class="card-title">Daily Sales</h4>
						<p class="card-category">
							<span class="text-success"><i class="fa fa-long-arrow-up"></i> 55% </span> increase in today sales.</p>
					</div>
					<div class="card-footer">
						<div class="stats">
							<i class="material-icons">access_time</i> updated 4 minutes ago
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card card-chart">
					<div class="card-header card-header-warning">
						<div class="ct-chart" id="websiteViewsChart"></div>
					</div>
					<div class="card-body">
						<h4 class="card-title">Email Subscriptions</h4>
						<p class="card-category">Last Campaign Performance</p>
					</div>
					<div class="card-footer">
						<div class="stats">
							<i class="material-icons">access_time</i> campaign sent 2 days ago
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card card-chart">
					<div class="card-header card-header-danger">
						<div class="ct-chart" id="completedTasksChart"></div>
					</div>
					<div class="card-body">
						<h4 class="card-title">Completed Tasks</h4>
						<p class="card-category">Last Campaign Performance</p>
					</div>
					<div class="card-footer">
						<div class="stats">
							<i class="material-icons">access_time</i> campaign sent 2 days ago
						</div>
					</div>
				</div>
			</div>
		</div> -->
		<div class="row">
			<div class="col-lg-12 col-md-12">
				<div class="card">
					<div class="card-header card-header-tabs card-header-success">
						<div class="nav-tabs-navigation">
							<div class="nav-tabs-wrapper">
								<span class="nav-tabs-title">最近更新：</span>
								<ul class="nav nav-tabs" data-tabs="tabs">
									<li class="nav-item">
										<a class="nav-link active" href="#catalogues" data-toggle="tab">
											<i class="material-icons">library_books</i> 目錄
											<div class="ripple-container"></div>
										</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="#products" data-toggle="tab">
											<i class="material-icons">store</i> 產品
											<div class="ripple-container"></div>
										</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="#stories" data-toggle="tab">
											<i class="material-icons">info_outline</i> 消息
											<div class="ripple-container"></div>
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="card-body">
						<div class="tab-content">
							<% if Catalogue.all.size > 0 %>
								<div class="tab-pane active" id="catalogues">
									<table class="table">
										<tbody>
											<% Catalogue.order(updated_at: :desc).limit(5).each do |catalogue| %>
											<tr>
												<td><%= catalogue.name %></td>
												<td class="td-actions text-right">
													<%= link_to edit_admin_catalogue_path(catalogue, dashboard: true), title: "編輯", class: "btn btn-link btn-primary btn-just-icon" do %>
														<i class="material-icons">edit</i>
													<% end %>
													<%= link_to admin_catalogue_path(catalogue), method: :delete, data: { confirm: I18n.t("text.confirm_destroy") }, title: "永久刪除" ,class: "btn btn-link btn-danger btn-just-icon" do %>
														<i class="material-icons">delete_forever</i>
													<% end %>
												</td>
											</tr>
											<% end %>
										</tbody>
									</table>
								</div>
							<% end %>
							<% if Product.all.size > 0 %>
								<div class="tab-pane" id="products">
									<table class="table">
										<tbody>
											<% Product.order(updated_at: :desc).limit(5).each do |product| %>
											<tr>
												<td><%= product.name %></td>
												<td class="td-actions text-right">
													<%= link_to edit_admin_product_path(product, dashboard: true), title: "編輯", class: "btn btn-link btn-primary btn-just-icon" do %>
														<i class="material-icons">edit</i>
													<% end %>
													<%= link_to admin_product_path(product), method: :delete, data: { confirm: I18n.t("text.confirm_destroy") }, title: "永久刪除" ,class: "btn btn-link btn-danger btn-just-icon" do %>
														<i class="material-icons">delete_forever</i>
													<% end %>
												</td>
											</tr>
											<% end %>
										</tbody>
									</table>
								</div>
							<% end %>
							<% if Story.all.size > 0 %>
								<div class="tab-pane" id="stories">
									<table class="table">
										<tbody>
											<% Story.order(updated_at: :desc).limit(5).each do |story| %>
											<tr>
												<td><%= story.title %></td>
												<td class="td-actions text-right">
													<%= link_to edit_admin_story_path(story, dashboard: true), title: "編輯", class: "btn btn-link btn-primary btn-just-icon" do %>
														<i class="material-icons">edit</i>
													<% end %>
													<%= link_to admin_story_path(story), method: :delete, data: { confirm: I18n.t("text.confirm_destroy") }, title: "永久刪除" ,class: "btn btn-link btn-danger btn-just-icon" do %>
														<i class="material-icons">delete_forever</i>
													<% end %>
												</td>
											</tr>
											<% end %>
										</tbody>
									</table>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
			<!-- <div class="col-lg-6 col-md-12">
				<div class="card">
					<div class="card-header card-header-warning">
						<h4 class="card-title">Employees Stats</h4>
						<p class="card-category">New employees on 15th September, 2016</p>
					</div>
					<div class="card-body table-responsive">
						<table class="table table-hover">
							<thead class="text-warning">
								<th>ID</th>
								<th>Name</th>
								<th>Salary</th>
								<th>Country</th>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Dakota Rice</td>
									<td>$36,738</td>
									<td>Niger</td>
								</tr>
								<tr>
									<td>2</td>
									<td>Minerva Hooper</td>
									<td>$23,789</td>
									<td>Curaçao</td>
								</tr>
								<tr>
									<td>3</td>
									<td>Sage Rodriguez</td>
									<td>$56,142</td>
									<td>Netherlands</td>
								</tr>
								<tr>
									<td>4</td>
									<td>Philip Chaney</td>
									<td>$38,735</td>
									<td>Korea, South</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div> -->
		</div>
	</div>
</div>

app/views/admin/pages/test.html.erb
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body">
						

						<table class="table-hover">
							<thead>
								<tr>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								<th>wfjoiwefjowifjow</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
								<tr>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
									<td>wfwefwfwfowkpfkwpfkpwkfpo</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<style>
	td, th {
		text-align: center;
	}
	.table-bordered thead td, .table-bordered thead th {
		border-bottom-width: 1px;
	}
</style>

<script type="text/javascript">
    $('table').fixedHeaderTable({ footer: true, cloneHeadToFoot: true, fixedColumn: true });
</script>

app/views/admin/pages/test2.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="container">
              <table>
                  <tr>
                    <td class="fixed">aaa</td>
                    <td>a</td>
                    <td>b</td>
                    <td>c</td>
                    <td>d</td>
                    <td>e</td>
                    <td>f</td>
                    <td>a</td>
                    <td>b</td>
                    <td>c</td>
                    <td>d</td>
                    <td>e</td>
                    <td>f</td>
                    <td>a</td>
                    <td>b</td>
                    <td>c</td>
                    <td>d</td>
                    <td>e</td>
                    <td>f</td>
                    <td>a</td>
                    <td>b</td>
                    <td>c</td>
                    <td>d</td>
                    <td>e</td>
                    <td>f</td>
                </tr>
                <tr>
                    <td class="fixed">bbb</td>
                    <td>a</td>
                    <td>b</td>
                    <td>c</td>
                    <td>d</td>
                    <td>e</td>
                    <td>f</td>
                    <td>a</td>
                    <td>b</td>
                    <td>c</td>
                    <td>d</td>
                    <td>e</td>
                    <td>f</td>
                    <td>a</td>
                    <td>b</td>
                    <td>c</td>
                    <td>d</td>
                    <td>e</td>
                    <td>f</td>
                    <td>a</td>
                    <td>b</td>
                    <td>c</td>
                    <td>d</td>
                    <td>e</td>
                    <td>f</td>
                </tr>
            </table>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>
<style type="text/css">
td, th {
  min-width: 50px;
}

.container {
  overflow-x: scroll;
  margin-left: 50px;
}

.fixed {
  position: absolute;
  left: 0;
  background: #aaa;
}

</style>

<script type="text/javascript">
    $('selector').fixedHeaderTable({ footer: true, cloneHeadToFoot: true, fixedColumn: true });
</script>