config/routes.rb
Rails.application.routes.draw do
	root "pages#home"
	scope "(:locale)", locale: /en|zh-TW/ do
		root "pages#home"
		controller :pages do
			get 'home', to: "pages#home"
			get 'about', to: "pages#about"
		  get 'products', to: "pages#products"
		  get 'contact', to: "pages#contact_us"
		  get 'download', to: "pages#download"
		end
    resources :products
    resources :stories
    resources :catalogues
  	resources :categories do
      member do
        get "children", to: "categories#children"
        get "products", to: "categories#products"
      end
    end
    post 'contact_us', to: "contacts#create"
	end

  namespace :admin do
    root to: "pages#home"
    get "pages/home"
    resources :users, only: [:edit, :update]
    resources :stories
    resources :products do
      collection do
        post "reorder"
      end
    end
    resources :varieties, except: [:show]
  	resources :catalogues
  	resources :categories
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/partials/_footer.html.erb
<footer class="footer ">
    <div class="container-fluid">
        <nav class="float-sm-left">
            <ul>
                <li>
                    <a href="https://shiftstudioco.com">
                        SHIFT STUDIO
                    </a>
                </li>
                <li>
                    <a href="https://shiftstudioco.com/about">
                        About Us
                    </a>
                </li>
                <li>
                    <a href="https://shiftstudioco.com/works">
                        Works
                    </a>
                </li>
                <li>
                    <a href="https://shiftstudioco.com/members">
                        Members
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright float-sm-right">
            &copy; <%= Time.new.year %>, made with <i class="material-icons">favorite</i> by
            <a href="https://shiftstudioco.com" target="_blank">SHIFT STUDIO</a>
        </div>
    </div>
</footer>

app/views/admin/partials/_nav.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute fixed-top">
	<div class="container-fluid">
    <div class="navbar-wrapper">
      <div class="navbar-minimize">
        <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
            <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
            <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
        <div class="ripple-container"></div></button>
      </div>
			<a class="navbar-brand" href="#pablo"><%= @nav_title %></a>
		</div>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="sr-only">Toggle navigation</span>
			<span class="navbar-toggler-icon icon-bar"></span>
			<span class="navbar-toggler-icon icon-bar"></span>
			<span class="navbar-toggler-icon icon-bar"></span>
		</button>

	    <div class="collapse navbar-collapse justify-content-end">
  			<ul class="navbar-nav">
  				<li class="nav-item">
  					<a class="nav-link" href="/admin">
              <i class="material-icons">dashboard</i>
  						<p>
                <span class="d-lg-none d-md-block">Stats</span>
              </p>
  					</a>
  				</li>
  			</ul>
	    </div>
	</div>
</nav>
<!-- End Navbar -->

app/views/admin/partials/_sidebar.html.erb
<div class="sidebar" data-color="rose" data-background-color="black" data-image="/img/Hero1_1280x800.png">
  <!--
  Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

  Tip 2: you can also add an image using data-image tag
  -->

  <div class="logo">
    <a href="/" class="simple-text logo-mini">
      <img src="/img/logo.svg">
    </a>

    <a href="/" class="simple-text logo-normal">
      弘優科技
    </a>

  </div>

  <% if user_signed_in? %>
    <div class="sidebar-wrapper">
      <div class="user">
        <!-- <div class="photo">
          <img src="/img/avatar.jpg" alt="Admin"/>
        </div> -->
        <div class="user-info">
          <a data-toggle="collapse" href="#collapseExample" class="username">
            <span>
              Admin
              <b class="caret"></b>
            </span>
          </a>
          <div class="collapse" id="collapseExample">
            <ul class="nav">
              <li class="nav-item">
                <%= link_to admin_logout_path, class: "nav-link", method: :delete do %>
                  <span class="sidebar-normal">登出</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to edit_admin_user_path(current_user), class: "nav-link" do %>
                  <span class="sidebar-normal">更改密碼</span>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <ul class="nav">
        <li class="nav-item <%= 'active' if current_page?(admin_root_path) %>">
          <a class="nav-link" href="/admin">
            <i class="material-icons">dashboard</i>
            <p> 主控台 </p>
          </a>
        </li>

        <li class="nav-item <%= 'active' if current_page?(admin_stories_path) %>">
          <a class="nav-link" href="/admin/stories">
            <i class="material-icons">info_outline</i>
            <p><%= Story.model_name.human %> </p>
          </a>
        </li>

        <li class="nav-item <%= 'active' if current_page?(admin_catalogues_path) %>">
          <a class="nav-link" href="/admin/catalogues">
            <i class="material-icons">library_books</i>
            <p><%= Catalogue.model_name.human %></p>
          </a>
        </li>

        <li class="nav-item <%= 'active' if current_page?(admin_categories_path) %>">
          <a class="nav-link" href="/admin/categories">
            <i class="material-icons">category</i>
            <p><%= Category.model_name.human %></p>
          </a>
        </li>

        <li class="nav-item <%= 'active' if current_page?(admin_products_path) || current_page?(admin_categories_path) %>">
          <a class="nav-link" data-toggle="collapse" href="#productCatagories" aria-expanded="<%= current_page?(admin_products_path) || current_page?(admin_categories_path) %>">
            <i class="material-icons">store</i>
            <p><%= Product.model_name.human %><b class="caret"></b></p>
          </a>

          <div class="collapse <%= 'show' if current_page?(admin_products_path) || current_page?(admin_categories_path) %>" id="productCatagories">
            <ul class="nav">
              <% Category.roots.each do |root| %>
              <li class="nav-item <%= 'active' if params[:category_id].to_i == root.id %>">
                <%= link_to admin_products_path(category_id: root.id), class: "nav-link" do %>
                <p><%= root.name %></p>
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </li>
      <!-- <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#languages">
      <i class="material-icons">language</i>
      <p> 語系
      <b class="caret"></b>
      </p>
      </a>

      <div class="collapse" id="languages">
      <ul class="nav">
      <li class="nav-item">
      <a class="nav-link" href="<%#= url_for(locale: 'en') %>">
      <span class="sidebar-mini"> EN </span>
      <span class="sidebar-normal"> English </span>
      </a>
      </li>
      <li class="nav-item">
      <a class="nav-link" href="<%#= url_for(locale: 'zh-TW') %>">
      <span class="sidebar-mini"> 繁 </span>
      <span class="sidebar-normal"> 繁體中文 </span>
      </a>
      </li>
      </ul>
      </div>
      </li> -->

      </ul>
  </div>
  <% end %>
</div>