config/routes.rb
Rails.application.routes.draw do
	root "pages#home"
	scope "(:locale)", locale: /en|zh-TW/ do
		root "pages#home"
		controller :pages do
			get 'home', to: "pages#home"
			get 'about', to: "pages#about"
		  get 'products', to: "pages#products"
		  get 'contact', to: "pages#contact_us"
		  get 'download', to: "pages#download"
		end
    resources :products
    resources :stories
    resources :catalogues
  	resources :categories do
      member do
        get "children", to: "categories#children"
        get "products", to: "categories#products"
      end
    end
    post 'contact_us', to: "contacts#create"
	end

  namespace :admin do
    root to: "pages#home"
    get "pages/home"
    resources :users, only: [:edit, :update]
    resources :stories
    resources :products do
      collection do
        post "reorder"
      end
    end
    resources :varieties, except: [:show]
  	resources :catalogues
  	resources :categories
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	validates :zh_name, presence: { message: "中文、英文標題至少需填寫一個。" }, unless: Proc.new { |p| p.twins? || p.en_name.present? }
	belongs_to :category, counter_cache: true
	has_many :varieties, dependent: :destroy
	has_many_attached :images
	has_one_attached :file
	enum status: { draft: 0, published: 1 }

	belongs_to :twin, class_name: "Product", foreign_key: "twin_id", optional: true
	scope :alone, -> { where(twin_id: nil) }
	after_destroy :detroy_twins!

	def twins?
		twin_id.present?
	end

	def detroy_twins!
		# puts "callback is called"
		twins = Product.where(twin_id: self.id)
		if twins.present?
			twins.map(&:destroy!)
		end
	end

	def name
		p = twins? ? self.twin : self
		if p.en_name.present? && p.zh_name.present?
			I18n.locale == :en ? p.en_name : p.zh_name
		else
			p.en_name.present? ? p.en_name : p.zh_name
		end
	end

	def t_images
		twins? ? twin.images : images
	end

	def t_file
		twins? ? twin.file : file
	end

	def admin_name
		self.twins? ? name + "(複製)" : name
	end

	def description
		p = twins? ? self.twin : self
		if p.en_description.present? && p.zh_description.present?
			I18n.locale == :en ? p.en_description : p.zh_description
		else
			p.en_description.present? ? p.en_description : p.zh_description
		end
	end

	def all_variety_feature_names
		p = twins? ? self.twin : self
		if p.varieties.present?
			top_features = p.varieties.map do |va|
				va.top_feature_names
			end
			normal_features = p.varieties.map do |va|
				va.normal_feature_names
			end
			top_features.flatten.uniq + normal_features.flatten.uniq
		else
			[]
		end
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
	layout 'admin'
	before_action :set_product, except: [:index, :create, :new, :reorder]

	def index
		disable_turbolinks_cache
		@nav_title = "產品資訊"
		@category = Category.find_by_id(params[:category_id])
		@products = if @category.present?
			Product.includes(:category, :twin).where(category_id: @category.self_and_descendants.pluck(:id))
		else
			Product.includes(:category, :twin).all
		end.order(ordering: :asc, id: :desc)
	end

	def new
		@product = Product.new
	end

	def create
		if product_params.has_key?(:twin_id) && product_params[:twin_id].present?
			@product = Product.new(twin_product_params)
		else
			@product = Product.new(product_params)
		end

		if @product.save
      flash[:success] = "建立成功。 "
      redirect_to admin_products_url(category_id: @product.category_id)
    else
    	flash.now[:danger] = @product.errors.messages.values.reject { |v| v.empty? }.join("<br>")
      render :new
    end
	end

	def show
	end

	def edit
	end

	def update
		if product_params.has_key?(:twin_id) && product_params[:twin_id].present?
			if @product.update(twin_product_params)
				flash[:success] = "更新成功。 "
	      redirect_to edit_admin_product_url(@product)
	    else
	    	flash.now[:danger] = @product.errors.messages.values.reject { |v| v.empty? }.join("<br>")
	      render :edit
	    end
		else
			product_params2 = product_params
			if product_params.has_key?(:file) && product_params[:file].blank?
				product_params2 = product_params2.except(:file)
				@product.file.purge_later if @product.file.attached?
			end
			if @product.update(product_params2.except(:images))
	      @product.images.where(id: params[:product][:remove_images].keys).map(&:purge_later) if params[:product][:remove_images].present?
	      @product.images.attach(params[:product][:images]) if params[:product][:images]
	      flash[:success] = "更新成功。 "
	      redirect_to edit_admin_product_url(@product)
	    else
	    	flash.now[:danger] = @product.errors.messages.values.reject { |v| v.empty? }.join("<br>")
	      render :edit
	    end
	  end
	end

	def destroy
		if @product.destroy
			flash[:success] = "刪除成功。"
		else
			flash[:danger] = "刪除失敗。"
		end
		redirect_to admin_products_url
	end

	def reorder
		params[:products].each do |id, ordering_hash|
			product = Product.find(id)
			if product.present?
				product.update(ordering: ordering_hash["ordering"])
			end
		end
	end

	private

	def set_product
		@product = Product.includes(:varieties, varieties: :features).with_attached_images.find(params[:id])
	end

	def twin_product_params
		params.require(:product).permit(:twin_id, :category_id, :status)
	end

	def product_params
		params.require(:product).permit(:twin_id, :category_id, :ordering, :en_name, :zh_name, :en_description, :zh_description, :status, :file, images: [])
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		@custom_footer = true
		# product = Product.find(params[:id])
		product = Product.includes(varieties: :features).with_attached_images.with_attached_file.find(params[:id])
		@product = if product.twins?
			product.twin
		else
			product
		end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="card-body ">
	<%= form_for [:admin, product] do |f| %>
		<% @form_id = f.options[:html][:id] %>

		<% unless f.object.persisted? && Product.where(twin_id: f.object.id).present? %>
			<div class="form-group bmd-form-group">
				<%= f.label :twin_id %>
				<%= f.select :twin_id, Product.alone.pluck(:zh_name, :id), { include_blank: "不複製" }, class: "form-control select2 searchable" %>
			</div>
		<% end %>

		<div class="form-group bmd-form-group">
			<%= f.label :category_id %>
			<%= f.select :category_id, Category.series.pluck(:zh_name, :id), { selected: product.category_id || params[:category_id] }, class: "form-control select2" %>
		</div>

		<div class="twins_disable <%= 'd-none' if f.object.twins? %>">
			<div class="form-group bmd-form-group">
				<%= f.label :zh_name, class: "bmd-label-floating" %>
				<%= f.text_field :zh_name, class: "form-control" %>
			</div>
			<div class="form-group bmd-form-group">
				<%= f.label :zh_description, class: "bmd-label-floating" %>
				<%= f.text_area :zh_description, class: "form-control", rows: 7 %>
			</div>
			
			<div class="clearfix my-5"></div>

			<div class="form-group bmd-form-group">
				<%= f.label :en_name, class: "bmd-label-floating" %>
				<%= f.text_field :en_name, class: "form-control" %>
			</div>
			<div class="form-group bmd-form-group">
				<%= f.label :en_description, class: "bmd-label-floating" %>
				<%= f.text_area :en_description, class: "form-control", rows: 7 %>
			</div>
			
			<div class="clearfix my-5"></div>

			<%= render "products/comparison_table", product: @product %>

			<div class="clearfix my-5"></div>

			<div class="form-group bmd-form-group">
		  	<% images_exist = f.object.images.attached? %>
		  	<label>產品圖片</label>
		    <div class="d-flex flex-wrap fileinput <%= images_exist ? 'fileinput-exists' : 'fileinput-new' %> text-center">
		    	<% if images_exist %>
	        	<% product.images.each do |img| %>
	        		<div class="uploaded_image_wrapper mb-5">
		        		<div class="fileinput-preview fileinput-exists thumbnail" style="">
					      	<% if img.previewable? %>
						        <%= link_to(image_tag(img.preview(resize: "600x600")),  rails_blob_path(img, disposition: "attachment")) %>
					      	<% elsif img.variable? %>
					        	<%= link_to(image_tag(img.variant(resize: "600x600")), rails_blob_path(img, disposition: "attachment")) %>
					      	<% else %>
						      	<div class="my-3">
						        	<%= link_to "下載附件 #{img.filename.to_s}", rails_blob_path(img, disposition: "attachment") %>
						        </div>
					      	<% end %>
					      </div>
					      <!-- <a href="#" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> 移除</a> -->
					      <div class="form-check mt-1">
		              <label class="form-check-label">
		                <!-- <input class="form-check-input" type="checkbox" value="" checked=""> Checked -->
							      <%= check_box_tag "product[remove_images][#{img.id}]", "true", false, { class: "form-check-input" } %> 移除
		                <span class="form-check-sign">
		                  <span class="check"></span>
		                </span>
		              </label>
		            </div>
		          </div>
			      <% end %>
			    <% end %>
				  <div style="flex-basis: 100%;">
		        <span class="btn btn-rose btn-round btn-file float-left">
		          <span class="fileinput-new">選擇圖片</span>
		          <span class="fileinput-exists">上傳更多</span>
		          <input type="hidden">
		          <%= f.file_field :images, multiple: true, accept: ".png, .jpg, .jpeg", class: "previewable" %>
		        	<div class="ripple-container"></div>
		      	</span>
		        <!-- <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> 移除</a> -->
		      </div>
		      <% if product.errors[:images].present? %>
		        <div class="invalid-feedback">
		          <%= product.errors[:images].join(", ") %>
		        </div>
		      <% end %>
		  	</div>
		  	<label id="newImagePreviewLabel" class="d-none">尚未上傳的圖片</label>
		  	<div id="newImagePreview" class="d-flex flex-wrap mb-5"></div>
		  </div>

		  <div class="clearfix my-5"></div>

		  <div class="form-group bmd-form-group">
				<% file_exist = f.object.file.attached? %>
		    <label>目錄檔案</label><br>
		    <div class="fileinput <%= file_exist ? 'fileinput-exists' : 'fileinput-new' %> text-center" data-provides="fileinput">
		    	<div class="fileinput-preview fileinput-exists thumbnail" style="">
		      	<% if file_exist %>
		        	<% if product.file.previewable? %>
				        <%= link_to(image_tag(product.file.preview(resize: "600x600>")),  rails_blob_path(product.file, disposition: "attachment")) %>
			      	<% elsif product.file.variable? %>
			        	<%= link_to(image_tag(product.file.variant(resize: "600x600")), rails_blob_path(product.file, disposition: "attachment")) %>
			      	<% else %>
				      	<div class="my-3">
				        	<%= link_to "下載附件 #{product.file.filename.to_s}", rails_blob_path(product.file, disposition: "attachment") %>
				        </div>
			      	<% end %>
			    	<% end %>
			    </div>
			    <br>
	        <span class="btn btn-rose btn-round btn-file">
	          <span class="fileinput-new">選擇檔案</span>
	          <span class="fileinput-exists">更換</span>
	          <input type="hidden">
	          <%= f.file_field :file, accept: ".png, .jpg, .jpeg, .pdf" %>
	        	<div class="ripple-container"></div>
	      	</span>
	        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> 移除</a>
	      </div>
		  </div>  
			
			<div class="clearfix my-5"></div>

		</div>

		<div class="form-group bmd-form-group">
			<div class="togglebutton">
		  	<label>
	  			<%= f.check_box :status, {}, "published", "draft" %>
          <span class="toggle bg-brand"></span>
            上架至前台
		  	</label>
		  </div>
		</div>

	<% end %><!-- form_for END -->
</div>

<div class="card-footer ">
	<%= submit_tag I18n.t("helpers.submit.#{action_name}"), class: "btn btn-fill btn-brand", form: @form_id %>
	<% if product.persisted? %>
		<%= link_to I18n.t("text.destroy"), admin_product_path(product), class: "btn btn-fill btn-danger btn-sm float-right", method: :delete, data: { confirm: "這會刪除產品資料，並且無法復原。若這是主要產品，同時也會刪除它的所有複製品。真的要繼續嗎？" } %>
	<% end %>
</div>

<script>
	$(document).on('turbolinks:load', function() {
		setFormValidation("<%= '#' + @form_id %>");
	})
</script>

app/views/admin/products/_product.html.erb
<tr>
	<td></td>
	<td><%= product.category.ancestors_names %></td>
	<td class="truncate"><%= product.admin_name %></td>
	<td><%= simple_format product.description.to_s.truncate(120) %></td>
	<td>
		<span class="badge<%= product.published? ? ' btn-brand' : ' btn-secondary' %>"><%= I18n.t("activerecord.product_status.#{product.status}") %></span>
	</td>
	<td>
		<%= text_field_tag "products[#{product.id}][ordering]", product.ordering, class: "product-ordering-input form-control", style: "max-width: 30px;" %>
	</td>
	<td class="text-right">
		<%= link_to edit_admin_product_path(product), class: "btn btn-link btn-primary btn-just-icon" do %>
			<i class="material-icons">edit</i>
		<% end %>
		<%= link_to admin_product_path(product), method: :delete, data: { confirm: "這會刪除產品資料，並且無法復原。若這是主要產品，同時也會刪除它的所有複製品。真的要繼續嗎？" }, class: "btn btn-link btn-danger btn-just-icon" do %>
			<i class="material-icons">delete_forever</i>
		<% end %>
	</td>
</tr>

app/views/admin/products/edit.html.erb
<div class="card">
	<div class="card-header card-header-danger card-header-icon">
		<div class="card-icon">
			<i class="material-icons">store</i>
		</div>
		<h4 class="card-title"><%= I18n.t("text.#{action_name}") %><%= Product.model_name.human %> <small><%= link_to "返回 #{@product.category.name}", admin_products_path(category_id: @product.category_id), class: "text-info" %></small></h4>
	</div>
	<%= render "form", product: @product %>
</div>

app/views/admin/products/index.html.erb
<div class="card">
	<div class="card-header card-header-danger card-header-icon">
		<div class="card-icon">
			<i class="material-icons">store</i>
		</div>
		<% if @category.present? && @category.level == Category.total_level %>
			<%= link_to new_admin_product_path(category_id: params[:category_id]) do %>
				<div class="card-icon rounded-circle float-right newBtn">
					<i class="material-icons">add</i>
				</div>
			<% end %>
		<% end %>
		<% if @category.present? && @category.level == 0 %>
			<%= link_to reorder_admin_products_path, id: "submit_ordering_inputs" do %>
				<div class="card-icon rounded-circle float-right subBtn" style="margin-right: 20px;">
					<i class="material-icons">save</i>
				</div>
			<% end %>
		<% end %>
		<h4 class="card-title"><%= Product.model_name.human count: 2 %></h4>
	</div>
	<div class="card-body">
		<div class="toolbar">
			<!--        Here you can write extra buttons/actions for the toolbar         -->
		</div>
		<div class="material-datatables">
			<table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
				<thead>
					<tr>
						<th class="disabled-sorting"></th>
						<th class="all"><%= Product.human_attribute_name(:category) %></th>
						<th class="all"><%= Product.human_attribute_name(:name) %></th>
						<th class="none"><%= Product.human_attribute_name(:description) %></th>
						<th><%= Product.human_attribute_name(:status) %></th>
						<th><%= Product.human_attribute_name(:ordering) %></th>
						<th class="disabled-sorting text-right"><%= I18n.t("text.actions") %></th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th class="disabled-sorting"></th>
						<th class="all"><%= Product.human_attribute_name(:category) %></th>
						<th class="all"><%= Product.human_attribute_name(:name) %></th>
						<th class="none"><%= Product.human_attribute_name(:description) %></th>
						<th><%= Product.human_attribute_name(:status) %></th>
						<th><%= Product.human_attribute_name(:ordering) %></th>
						<th class="disabled-sorting text-right"><%= I18n.t("text.actions") %></th>
					</tr>
				</tfoot>
				<tbody>
					<%= render @products %>
				</tbody>
			</table>
		</div>
	</div><!-- end content-->
</div>

<script type="text/javascript">
	document.querySelector("#submit_ordering_inputs").addEventListener("click", function(e) {
		e.preventDefault()
		var url = this.getAttribute("href")
		$.ajax({
			url: url,
			method: "post",
			data: $(".product-ordering-input").serialize()
		}).done(function() {
			location.reload()
		})
	})
</script>

app/views/admin/products/new.html.erb
<div class="content">
	<div class="container-fluid">
		<div class="card ">
			<div class="card-header card-header-danger card-header-icon">
				<div class="card-icon">
					<i class="material-icons">store</i>
				</div>
				<h4 class="card-title"><%= I18n.t("text.#{action_name}") %><%= Product.model_name.human %></h4>
			</div>
			<%= render "form", product: @product %>
		</div>
	</div>
</div>

app/views/admin/products/show.html.erb
<div class="card">
	<div class="card-header card-header-default card-header-icon">
		<div class="card-icon">
			<i class="material-icons">store</i>
		</div>
		<%= link_to admin_categories_path do %>
			<div class="card-icon rounded-circle float-right subBtn ml-3">
				<i class="material-icons">category</i>
			</div>
		<% end %>
		<%= link_to edit_admin_product_path(@product) do %>
			<div class="card-icon rounded-circle float-right newBtn">
				<i class="material-icons">edit</i>
			</div>
		<% end %>
		<h4 class="card-title"><%= I18n.t("text.#{action_name}") %><%= Product.model_name.human %></h4>
	</div>
	<%= render "form", product: @product %>
</div>