config/routes.rb
Rails.application.routes.draw do
	root "pages#home"
	scope "(:locale)", locale: /en|zh-TW/ do
		root "pages#home"
		controller :pages do
			get 'home', to: "pages#home"
			get 'about', to: "pages#about"
		  get 'products', to: "pages#products"
		  get 'contact', to: "pages#contact_us"
		  get 'download', to: "pages#download"
		end
    resources :products
    resources :stories
    resources :catalogues
  	resources :categories do
      member do
        get "children", to: "categories#children"
        get "products", to: "categories#products"
      end
    end
    post 'contact_us', to: "contacts#create"
	end

  namespace :admin do
    root to: "pages#home"
    get "pages/home"
    resources :users, only: [:edit, :update]
    resources :stories
    resources :products do
      collection do
        post "reorder"
      end
    end
    resources :varieties, except: [:show]
  	resources :catalogues
  	resources :categories
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	validates :zh_name, presence: { message: "中文、英文標題至少需填寫一個。" }, unless: Proc.new { |p| p.twins? || p.en_name.present? }
	belongs_to :category, counter_cache: true
	has_many :varieties, dependent: :destroy
	has_many_attached :images
	has_one_attached :file
	enum status: { draft: 0, published: 1 }

	belongs_to :twin, class_name: "Product", foreign_key: "twin_id", optional: true
	scope :alone, -> { where(twin_id: nil) }
	after_destroy :detroy_twins!

	def twins?
		twin_id.present?
	end

	def detroy_twins!
		# puts "callback is called"
		twins = Product.where(twin_id: self.id)
		if twins.present?
			twins.map(&:destroy!)
		end
	end

	def name
		p = twins? ? self.twin : self
		if p.en_name.present? && p.zh_name.present?
			I18n.locale == :en ? p.en_name : p.zh_name
		else
			p.en_name.present? ? p.en_name : p.zh_name
		end
	end

	def t_images
		twins? ? twin.images : images
	end

	def t_file
		twins? ? twin.file : file
	end

	def admin_name
		self.twins? ? name + "(複製)" : name
	end

	def description
		p = twins? ? self.twin : self
		if p.en_description.present? && p.zh_description.present?
			I18n.locale == :en ? p.en_description : p.zh_description
		else
			p.en_description.present? ? p.en_description : p.zh_description
		end
	end

	def all_variety_feature_names
		p = twins? ? self.twin : self
		if p.varieties.present?
			top_features = p.varieties.map do |va|
				va.top_feature_names
			end
			normal_features = p.varieties.map do |va|
				va.normal_feature_names
			end
			top_features.flatten.uniq + normal_features.flatten.uniq
		else
			[]
		end
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
	layout 'admin'
	before_action :set_product, except: [:index, :create, :new, :reorder]

	def index
		disable_turbolinks_cache
		@nav_title = "產品資訊"
		@category = Category.find_by_id(params[:category_id])
		@products = if @category.present?
			Product.includes(:category, :twin).where(category_id: @category.self_and_descendants.pluck(:id))
		else
			Product.includes(:category, :twin).all
		end.order(ordering: :asc, id: :desc)
	end

	def new
		@product = Product.new
	end

	def create
		if product_params.has_key?(:twin_id) && product_params[:twin_id].present?
			@product = Product.new(twin_product_params)
		else
			@product = Product.new(product_params)
		end

		if @product.save
      flash[:success] = "建立成功。 "
      redirect_to admin_products_url(category_id: @product.category_id)
    else
    	flash.now[:danger] = @product.errors.messages.values.reject { |v| v.empty? }.join("<br>")
      render :new
    end
	end

	def show
	end

	def edit
	end

	def update
		if product_params.has_key?(:twin_id) && product_params[:twin_id].present?
			if @product.update(twin_product_params)
				flash[:success] = "更新成功。 "
	      redirect_to edit_admin_product_url(@product)
	    else
	    	flash.now[:danger] = @product.errors.messages.values.reject { |v| v.empty? }.join("<br>")
	      render :edit
	    end
		else
			product_params2 = product_params
			if product_params.has_key?(:file) && product_params[:file].blank?
				product_params2 = product_params2.except(:file)
				@product.file.purge_later if @product.file.attached?
			end
			if @product.update(product_params2.except(:images))
	      @product.images.where(id: params[:product][:remove_images].keys).map(&:purge_later) if params[:product][:remove_images].present?
	      @product.images.attach(params[:product][:images]) if params[:product][:images]
	      flash[:success] = "更新成功。 "
	      redirect_to edit_admin_product_url(@product)
	    else
	    	flash.now[:danger] = @product.errors.messages.values.reject { |v| v.empty? }.join("<br>")
	      render :edit
	    end
	  end
	end

	def destroy
		if @product.destroy
			flash[:success] = "刪除成功。"
		else
			flash[:danger] = "刪除失敗。"
		end
		redirect_to admin_products_url
	end

	def reorder
		params[:products].each do |id, ordering_hash|
			product = Product.find(id)
			if product.present?
				product.update(ordering: ordering_hash["ordering"])
			end
		end
	end

	private

	def set_product
		@product = Product.includes(:varieties, varieties: :features).with_attached_images.find(params[:id])
	end

	def twin_product_params
		params.require(:product).permit(:twin_id, :category_id, :status)
	end

	def product_params
		params.require(:product).permit(:twin_id, :category_id, :ordering, :en_name, :zh_name, :en_description, :zh_description, :status, :file, images: [])
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		@custom_footer = true
		# product = Product.find(params[:id])
		product = Product.includes(varieties: :features).with_attached_images.with_attached_file.find(params[:id])
		@product = if product.twins?
			product.twin
		else
			product
		end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comparison_table.html.erb
<div class="product-comparison" id="js-choose-highlight-jump-here">
	<div class="product-data__block-title">型號規格</div>
	<% if product.persisted? && in_admin? %>
		<%= link_to new_admin_variety_path(product_id: product.id), class: "btn btn-brand" do %>
      <i class="material-icons">add</i> 建立型號
		<% end %>
	<% end %>
	<% if product.varieties.present? %>
		<div class="product-comparison__table-wrapper js-product-comparison__table-wrapper">
			<% names_array = product.all_variety_feature_names.flatten.uniq#.sort_by!{ |m| m.downcase } %>
			<table class="table text-center">
				<tbody>
					<tr class="attribute_names">
						<th nowrap="true">型號</th>
						<% names_array.each do |feature_name| %>
							<th nowrap="true"><%= feature_name %></th>
						<% end %>
					</tr>
					<% product.varieties.each do |va| %>
						<tr>
							<th nowrap="true" data-highlight="<%= va.id %>">
								<%= va.name %><br>
								<% if in_admin? %>
									<%= link_to edit_admin_variety_path(va), data: { turbolinks: false } do %>
										<i class="material-icons">edit</i>
									<% end %>
									<%= link_to admin_variety_path(va), method: :delete, data: { confirm: I18n.t("text.confirm_destroy") }, title: "永久刪除" ,class: "btn btn-link btn-danger btn-just-icon" do %>
										<i class="material-icons">delete_forever</i>
									<% end %>
								<% end %>
							</th>
							<% names_array.each_with_index do |feature_name, index| %>
								<% if va.features.where("zh_name LIKE :name OR en_name LIKE :name", name: feature_name).present? %>
									<% value = va.features.where("zh_name LIKE :name OR en_name LIKE :name", name: feature_name).first.value %>
									<td data-name="<%= feature_name %>" data-highlight="<%= va.id %>" rowspan=""><%= value %></td>
								<% else %>
									<td data-name="<%= feature_name %>" data-highlight="<%= va.id %>" rowspan="">X</td>
								<% end %>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% else %>
		<% if product.new_record? %>
			<small>請先建立產品本身資料，才能建立型號。</small>
		<% end %>
	<% end %>
</div>

app/views/products/_images_section.html.erb
<section class="d-flex align-content-end flex-column images-section js-images-section">
	<div class="d-flex align-items-end justify-content-center images-wrapper">
		<% if product.images.attached? %>
			<div class="image--active js-image--active"
			style='background-image: url("<%= rails_blob_path(product.images.first) %>"); background-image: url("<%= rails_blob_path(product.images.first) %>"); background-image: url("<%= rails_blob_path(product.images.first) %>");'></div>
			<div class="image--blur-bg js-image--blur-bg" style='background-image: url("<%= rails_blob_path(product.images.first) %>"); background-image: url("<%= rails_blob_path(product.images.first) %>"); background-image: url("<%= rails_blob_path(product.images.first) %>"); filter: blur(7px); opacity: 0.6;'></div>
			<div class="d-flex justify-content-between image-thumbs">
				<% product.images.each do |img| %>
					<%= image_tag img, class: "image--thumb js-image--thumb" %>
				<% end %>
			</div>
		<% else %>
			<!-- <div class="image--active"></div>
			<div class="d-flex justify-content-between images">
				<div class="image">
					<img src="">
				</div>
			</div> -->
		<% end %>
	</div>
</section>

app/views/products/_product.html.erb
	<%= link_to product_path(id: product), class: "product" do %>
		<% if product.t_images.attached? %>
			<div class="product__img" style='background: url("<%= rails_blob_path(product.t_images.first) %>") no-repeat center; background-size: contain;'></div>
		<% else %>
			<div class="product__img"></div>
		<% end %>
		<span class="product__category">
			<span class="product__category--brand"><%= product.category.parent.name %></span> - <span class="product__category--series"><%= product.category.name %></span>
		</span>
		<h3 class="product__name"><%= product.name %></h3>
	<% end %>

app/views/products/show.html.erb
<div class="d-flex sections">

	<%= render "images_section", product: @product %>

	<section class="d-flex align-content-end flex-column product-data-section">
		<div class="d-flex flex-column product-data">
			<span class="product-data__category v700">
				<%= link_to @product.category.parent.name, products_path(root_id: @product.category.try(:parent).try(:parent).id, brand_id: @product.category.try(:parent).id), class: "product-data__category--brand" %> - <span class="product__category--series"><%= @product.category.name %></span>
			</span>
			<div class="product-data__variety d-flex">
				<label for="product-data_variety_name" class="v700 mb-0 border-right-0">MDOEL</label>
				<%= select_tag :product_variety_name, options_from_collection_for_select(@product.varieties, "id", "zh_name"), prompt: "Choose one to highlight", class: 'form-control nt400 select2' %>
				<!-- <select name="product[model]" id="product_model" class="form-control v700">
					<option value="1">01 Life Science Animal Science</option>
					<option value="2">01 Life Science Animal Science</option>
					<option value="3">01 Life Science Animal Science</option>
				</select> -->
			</div>

			<h2 class="product-data__name js-product-data__name"><%= @product.name %></h2>

			<div class="product-data__detail">
				<div class="product-data__title">DETAIL</div>
				<div class="product-data__description nt100">
					<%= simple_format @product.description %>
				</div>
				<% if @product.t_file.attached? %>
					<%= link_to rails_blob_path(@product.t_file, disposition: "attachment"), id: "see_more_btn", class: "d-flex" do %>
						<div class="mr-auto align-self-center see_more_text download_dm_text nt500">廠商型錄下載</div>
					<% end %>
				<% end %>
			</div>

			<% if @product.varieties.present? %>
				<%= render "comparison_table", product: @product %>
			<% end %>

			<div class="related-products">
				<div class="product-data__block-title">RELATED PRODUCTS</div>
				<div class="related-products__products d-flex flex-wrap justify-content-between">
					<%= render @product.category.products.limit(4) %>
				</div>
			</div>
		</div>   <!-- #product_data_wrapper -->
		<%= render "common/footer" %>
	</section> <!-- product_data_section -->
</div>